services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: arrivals_board
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
